# STAGE 1 - generate a recipe file for dependencies
FROM rust as planner
WORKDIR /app
RUN cargo install cargo-chef
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

# STAGE 2 - build dependencies
FROM rust as cacher
WORKDIR /app
RUN cargo install cargo-chef
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json

# STAGE 3 - build source with cached dependencies
FROM rust as builder

ENV USER=web
ENV UID=1001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

COPY . /app
WORKDIR /app
COPY --from=cacher /app/target target
RUN cargo build

# STAGE 4 - build docker image
FROM rust

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder . /app
COPY --from=builder /app/Rocket.toml /app/Rocket.toml
COPY --from=builder /app/migrations /app/migrations

WORKDIR /app

USER web:web

# RUN cargo install sqlx-cli --no-default-features --features native-tls,postgres
# RUN cargo sqlx migrate run 
RUN cargo install cargo-watch
CMD ["cargo", "watch", "-x", "run"]
