version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./config/.env
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  postgres-data:
