# STAGE 1 - generate a recipe file for dependencies
FROM rust
WORKDIR /app
RUN cargo install cargo-watch
COPY . /app
CMD ["cargo", "watch", "-x", "run"]

# STAGE 4 - build docker image
# FROM gcr.io/distroless/cc-debian11

# COPY --from=builder /etc/passwd /etc/passwd
# COPY --from=builder /etc/group /etc/group

# COPY --from=builder /app/target/release/auth /app/auth
# COPY --from=builder /app/Rocket.toml /app/Rocket.toml

# WORKDIR /app

# USER web:web

# CMD ["./auth"]