version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    #   - /app/target/debug
    # network_mode: service:db
    ports:
      - "8080:8080"
    # command: sleep infinity
    restart: always

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
